services:
  - type: web
    name: bangla-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_webhook.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health